# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Custom vars
version:          1.0.1


# Setup
title:             Lab Notebook
tagline:          'Your Name'
description:      'Blah blah blah'
baseurl:          /sampleNotebook

paginate:         5

github:
  repo:           https://github.com/taddallas/sampleNotebook
