# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Custom vars
version:          1.0.1


# Setup
title:             lab notebook
tagline:          'Daniel Becker'
description:      'lab notebook'
baseurl:          /LabNotebook

paginate:         5

github:
  repo:           https://github.com/danieljbecker/LabNotebook
